- name: Create docker systemd directory
  file:
    path: "{{ systemd_docker_dir }}"
    state: directory
    mode: 0644

- name: Setup docker systemd configuration
  template:
    src: "systemd.docker-start"
    dest: "{{ systemd_docker_dir }}/docker-start.conf"
    mode: 0644
  notify: restart docker
