- name: Setup docker.socket conf
  copy:
    src=docker.socket
    dest=/lib/systemd/system/docker.socket
    mode=0644
  notify:
    - restart docker

- name: Setup docker.service conf
  copy:
    src=docker.service
    dest=/lib/systemd/system/docker.service
    mode=0644
  notify:
    - restart docker

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed
