- name: Run kubeadm init on master (wired)
  command: kubeadm init --skip-preflight-checks --token {{ kubeadm_token }} --pod-network-cidr={{ network.pod_subnet }}
  register: kubeadm_init
  when: wifi_enabled == false

- name: Run kubeadm init on master (wireless)
  command: kubeadm init --skip-preflight-checks --token {{ kubeadm_token }} --pod-network-cidr={{ network.pod_subnet }} --api-advertise-addresses={{ inventory_hostname }}
  register: kubeadm_init
  when: wifi_enabled == true

# - debug: var=kubeadm_init.stdout

- name: Copy flannel installation
  template: src=kube-flannel.yml dest=/etc/kubernetes/kube-flannel.yml

- name: Create flannel resources
  command: kubectl create -f /etc/kubernetes/kube-flannel.yml

- name: Download cluster configuration
  fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ playbook_dir }}/run/"
    flat: true

- name: Rename cluster configuration
  local_action: command mv {{ playbook_dir }}/run/admin.conf {{ playbook_dir }}/run/pi-cluster.cfg
