docker:
  #bind_host: "{{ inventory_hostname }}"
  bind_host: 127.0.0.1
  bind_port: 2375

systemd_docker_dir: "/etc/systemd/system/docker.service.d"

reset: false
network:
  bridge_ip: 10.244.0.1/16
  pod_subnet: 10.244.0.0/16
images:
  flannel: quay.io/coreos/flannel:v0.7.0-arm
k8s:
  # Timing is good for demos. Defaults are 5min eviction and 40s node grace period
  # TODO: Not yet put into the k8s configuration
  pod_eviction_timeout: 5s
  node_monitor_grace_period: 10s
debug_level: 2
